"""Framework-aware .gitignore presets and safe custom-pattern handling."""

from __future__ import annotations

import re
from typing import Iterable, List


BASE_PATTERNS = [
    "__pycache__/", "*.py[cod]", "*$py.class", "venv/", ".venv/", ".env/",
    ".env", ".env.*", "!.env.example", "*.log", "build/", "dist/", "*.egg-info/", ".vscode/", ".idea/",
    ".DS_Store", "Thumbs.db",
]

PRESETS = {
    "python": BASE_PATTERNS,
    "django": BASE_PATTERNS + ["db.sqlite3", "media/", "staticfiles/"],
    "node": ["node_modules/", ".npm/", ".yarn/", ".pnpm-store/", "coverage/", ".next/", "dist/", "*.log", ".env", ".env.*", "!.env.example", ".DS_Store"],
    "cpp": ["build/", "cmake-build-*/", "CMakeFiles/", "CMakeCache.txt", "compile_commands.json", "*.o", "*.obj", "*.exe", ".DS_Store"],
    "minimal": [".env", ".env.*", "!.env.example", "*.log", ".DS_Store"],
}

FRAMEWORK_PRESETS = {
    "django": "django",
    "native_cpp": "cpp",
    "react": "node",
    "node": "node",
}


def available_presets() -> List[str]:
    """Return public preset names in a stable order."""
    return ["framework", "python", "django", "node", "cpp", "minimal"]


def resolve_preset(preset: str | None, framework: str | None) -> str:
    """Resolve the framework alias and reject unknown preset names."""
    value = (preset or "framework").strip().lower().replace("-", "_")
    if value == "framework":
        return FRAMEWORK_PRESETS.get((framework or "").strip().lower(), "python")
    if value not in PRESETS:
        raise ValueError(f"Unknown .gitignore preset: {preset}")
    return value


def normalize_patterns(values: Iterable[str] | None) -> List[str]:
    """Accept CLI bracket lists or separate values and return unique patterns.

    ``[.env, logs/, *.local]`` and ``.env logs/ '*.local'`` are equivalent.
    Newlines and NUL bytes are rejected so an argument cannot silently create
    unrelated ignore rules.
    """
    patterns: List[str] = []
    if isinstance(values, str):
        values = [values]
    for raw in values or []:
        text = str(raw).strip()
        if not text:
            continue
        if "\x00" in text or "\n" in text or "\r" in text:
            raise ValueError(".gitignore patterns must be single-line values")
        if text.startswith("[") and text.endswith("]"):
            text = text[1:-1]
        for candidate in text.split(","):
            candidate = candidate.strip().replace("\\", "/")
            if not candidate:
                continue
            if "\x00" in candidate or "\n" in candidate or "\r" in candidate:
                raise ValueError(".gitignore patterns must be single-line values")
            if candidate not in patterns:
                patterns.append(candidate)
    return patterns


def render_gitignore(preset: str | None, framework: str | None, custom_patterns: Iterable[str] | None = None) -> str:
    """Build deterministic .gitignore content, retaining user pattern syntax."""
    preset_name = resolve_preset(preset, framework)
    rules = list(PRESETS[preset_name])
    for pattern in normalize_patterns(custom_patterns):
        if pattern not in rules:
            rules.append(pattern)

    header = [
        f"# Generated by init-app ({preset_name} preset)",
        "# Add project-specific rules below; negation rules such as !keep.txt are supported.",
        "",
    ]
    return "\n".join(header + rules) + "\n"
