"""Local, provider-neutral context bundles for RAG indexing."""

from __future__ import annotations

import json
from pathlib import Path
from typing import Dict, Iterable, List


SCHEMA_VERSION = "1.0"
EXCLUDED_DIRECTORY_NAMES = {
    ".git", ".hg", ".svn", "node_modules", "venv", ".venv", "__pycache__",
    ".mypy_cache", ".pytest_cache", ".ruff_cache", "dist", "build",
}
EXCLUDED_FILE_NAMES = {".env", ".env.local", ".env.production"}
EXCLUDED_SUFFIXES = {".pyc", ".pyo", ".so", ".dylib", ".dll", ".exe", ".db", ".sqlite", ".sqlite3"}


def _is_indexable(path: Path, root: Path) -> bool:
    """Apply conservative defaults before any local indexer reads a file."""
    relative = path.relative_to(root)
    if any(part in EXCLUDED_DIRECTORY_NAMES for part in relative.parts[:-1]):
        return False
    name = path.name.lower()
    return name not in EXCLUDED_FILE_NAMES and path.suffix.lower() not in EXCLUDED_SUFFIXES


def inventory_project(root: Path) -> List[str]:
    """Return a sorted, portable inventory without source content or secrets."""
    if not root.exists():
        return []
    return sorted(
        path.relative_to(root).as_posix()
        for path in root.rglob("*")
        if path.is_file() and _is_indexable(path, root)
    )


def build_context(manifest: Dict, root: Path, files: Iterable[str]) -> Dict:
    """Create the stable machine-readable hand-off for a local RAG service."""
    return {
        "schema_version": SCHEMA_VERSION,
        "kind": "init-app.local-rag-context",
        "project": {
            "name": manifest.get("project name", manifest.get("project_name", root.name)),
            "framework": manifest.get("fw_name", manifest.get("framework", "unknown")),
            "build_strategy": manifest.get("build strategy", manifest.get("build_strategy", "standard")),
            "database": manifest.get("database", "sqlite"),
            "app_name": manifest.get("app_name", "core_app"),
        },
        "architecture": {
            "custom_folders": manifest.get("custom_folders", []),
            "python_packages": [name for name, enabled in manifest.get("init_strategy", {}).items() if enabled],
            "infrastructure": manifest.get("infra_files", {}),
        },
        "indexing": {
            "mode": "local_only",
            "respect_gitignore": True,
            "exclude_directory_names": sorted(EXCLUDED_DIRECTORY_NAMES),
            "exclude_file_names": sorted(EXCLUDED_FILE_NAMES),
            "exclude_suffixes": sorted(EXCLUDED_SUFFIXES),
            "instructions": "Index text files only. Do not embed secrets, virtual environments, build output, or binary/database files.",
        },
        "inventory": {"files": list(files)},
    }


def write_project_context(root: Path, manifest: Dict) -> None:
    """Write a human and machine readable local-RAG onboarding bundle."""
    payload = build_context(manifest, root, inventory_project(root))
    state_dir = root / ".init-app"
    state_dir.mkdir(parents=True, exist_ok=True)
    (state_dir / "rag-context.json").write_text(json.dumps(payload, indent=2) + "\n", encoding="utf-8")

    markdown = f"""# Local RAG project context

This project was generated by init-app. Use `.init-app/rag-context.json` as the machine-readable bootstrap for a **local-only** RAG index.

## Project

- Framework: `{payload['project']['framework']}`
- Build strategy: `{payload['project']['build_strategy']}`
- Database: `{payload['project']['database']}`
- Application entry: `{payload['project']['app_name']}`

## Indexing contract

1. Read the current repository, then use the JSON inventory as a discovery aid—not as the source of truth after files change.
2. Respect `.gitignore` and the exclusions in `rag-context.json`.
3. Never index `.env` files, credentials, virtual environments, build output, binary files, or local databases.
4. Chunk source by file and language-aware symbols where possible; retain path and content-hash metadata for incremental updates.
5. Keep embeddings, vector stores, and model caches outside the repository or add their paths to `.gitignore`.

The context bundle contains metadata and paths only; it does not send project content to any provider.
"""
    docs_dir = root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)
    (docs_dir / "LOCAL_RAG.md").write_text(markdown, encoding="utf-8")
