/* 🔥 {{ project_name | upper }} Global UI System 
   Generated by: {{ APP_NAME }} v{{ __version__ }}
   Framework: {{ framework | capitalize }}
*/

@import url('https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700;800&family=JetBrains+Mono:wght@400;500&display=swap');

/* --- Dynamic Theme Variables --- */
:root {
    /* Base Variables */
    --{{ project_name | lower }}-primary: {{ "#2ba977" if framework == 'flask' else "#0070f3" }};
    
    /* Dark Mode (Default) */
    --bg: #0a0a0a;
    --card-bg: rgba(255, 255, 255, 0.03);
    --card-hover: rgba(255, 255, 255, 0.08);
    --text: #ededed;
    --muted: #888888;
    --border: rgba(255, 255, 255, 0.1);
    --accent: var(--{{ project_name | lower }}-primary);
    --nav-bg: rgba(10, 10, 10, 0.8);
}

[data-theme="light"] {
    --bg: #ffffff;
    --card-bg: #f9f9f9;
    --card-hover: #f0f0f0;
    --text: #171717;
    --muted: #666666;
    --border: rgba(0, 0, 0, 0.1);
    --accent: #0070f3; 
    --nav-bg: rgba(255, 255, 255, 0.8);
}

/* --- Framework Specific Accent Logic --- */
body.fastapi   { --accent: #05998b; --accent-glow: rgba(5, 153, 139, 0.1); }
body.flask     { --accent: #2ba977; --accent-glow: rgba(43, 169, 119, 0.1); }
body.django    { --accent: #092e20; --accent-glow: rgba(9, 46, 32, 0.2); }
body.bottle    { --accent: #0ea5e9; --accent-glow: rgba(14, 165, 233, 0.1); }
body.tornado   { --accent: #7b3fe4; --accent-glow: rgba(123, 63, 228, 0.1); }
body.pyramid   { --accent: #ff6b00; --accent-glow: rgba(255, 107, 0, 0.1); }

/* --- Core Styles --- */
* { margin: 0; padding: 0; box-sizing: border-box; }

body {
    background: var(--bg);
    color: var(--text);
    font-family: 'Inter', sans-serif;
    -webkit-font-smoothing: antialiased;
    min-height: 100vh;
    display: flex;
    flex-direction: column;
}

/* Project-Specific Wrapper Class from Generator */
.{{ project_name | lower }}-engine {
    border-top: 4px solid var(--accent);
}

/* --- Navigation & GitHub Button --- */
.nav {
    width: 100%;
    border-bottom: 1px solid var(--border);
    background: var(--nav-bg);
    backdrop-filter: blur(12px);
    position: sticky;
    top: 0;
    z-index: 1000;
}

.nav-content {
    max-width: 1100px;
    margin: 0 auto;
    padding: 1rem 2rem;
    display: flex;
    justify-content: space-between;
    align-items: center;
}

.github-btn {
    background: var(--text);
    color: var(--bg) !important;
    padding: 8px 16px;
    border-radius: 8px;
    font-weight: 600;
    font-size: 14px;
    display: flex;
    align-items: center;
    gap: 8px;
    transition: opacity 0.2s, transform 0.2s;
    text-decoration: none;
}

.github-btn:hover {
    opacity: 0.9;
    transform: translateY(-1px);
}

/* --- Pill Theme Toggle --- */
.theme-toggle {
    --toggle-width: 52px;
    --toggle-height: 26px;
    --circle-size: 20px;
    position: relative;
    width: var(--toggle-width);
    height: var(--toggle-height);
    background: var(--card-hover);
    border: 1px solid var(--border);
    border-radius: 100px;
    cursor: pointer;
    display: flex;
    align-items: center;
    padding: 0 3px;
    margin-left: 20px;
}

.toggle-circle {
    width: var(--circle-size);
    height: var(--circle-size);
    background: var(--accent);
    border-radius: 50%;
    transition: transform 0.3s cubic-bezier(0.4, 0, 0.2, 1);
}

[data-theme="dark"] .toggle-circle {
    transform: translateX(calc(var(--toggle-width) - var(--circle-size) - 8px));
}

/* --- Main Layout --- */
.page {
    flex: 1;
    max-width: 1100px;
    width: 100%;
    margin: 0 auto;
    padding: 80px 2rem;
}

h1 {
    font-size: clamp(2.5rem, 6vw, 3.5rem);
    font-weight: 800;
    letter-spacing: -0.05em;
    margin-bottom: 16px;
}

.dot { color: var(--accent); }

.subtitle {
    font-size: 1.25rem;
    color: var(--muted);
    margin-bottom: 48px;
    max-width: 600px;
}

/* --- Stats Grid (Populated from Constants) --- */
.info-grid {
    display: grid;
    grid-template-columns: repeat(auto-fit, minmax(280px, 1fr));
    gap: 20px;
    margin-bottom: 60px;
}

.card {
    background: var(--card-bg);
    border: 1px solid var(--border);
    border-radius: 16px;
    padding: 24px;
    transition: border-color 0.2s;
}

.card:hover {
    border-color: var(--accent);
}

.card strong {
    display: block;
    font-size: 11px;
    text-transform: uppercase;
    color: var(--accent);
    margin-bottom: 8px;
}

/* --- Tech Stack Icons --- */
.tech-stack {
    display: flex;
    gap: 32px;
    flex-wrap: wrap;
    padding-top: 20px;
}

.tech-item {
    display: flex;
    align-items: center;
    gap: 10px;
    opacity: 0.6;
    transition: opacity 0.3s;
}

.tech-item:hover { opacity: 1; }

.tech-item img {
    width: 24px;
    height: 24px;
    filter: drop-shadow(0 0 5px var(--accent-glow));
}

/* --- Footer --- */
.footer {
    padding: 40px 2rem;
    border-top: 1px solid var(--border);
    color: var(--muted);
    font-size: 14px;
}