/**
 * 🚀 {{ project_name | capitalize }} Interaction System
 * Generated by {{ APP_NAME }}
 */

console.log("🚀 {{ project_name }} UI Engine loaded");

document.addEventListener('DOMContentLoaded', () => {
    // 1. Initial Page Load Animation
    document.body.classList.add("loaded");

    // 2. Theme Orchestration
    const themeToggle = document.getElementById('theme-toggle');
    const storageKey = '{{ project_name | lower }}-theme';

    if (themeToggle) {
        themeToggle.addEventListener('click', () => {
            // Get current state from the <html> attribute
            const currentTheme = document.documentElement.getAttribute('data-theme');
            
            // Toggle logic
            const newTheme = currentTheme === 'dark' ? 'light' : 'dark';

            // Apply to DOM
            document.documentElement.setAttribute('data-theme', newTheme);
            
            // Persist preference
            localStorage.setItem(storageKey, newTheme);
            
            // Log with Framework-specific style
            const accentColor = getComputedStyle(document.body).getPropertyValue('--accent').trim();
            console.log(
                `%c {{ project_name | upper }} %c ${newTheme.toUpperCase()} MODE `,
                `background: ${accentColor}; color: #fff; font-weight: bold; border-radius: 3px 0 0 3px;`,
                `background: #222; color: ${accentColor}; font-weight: bold; border-radius: 0 3px 3px 0;`
            );
        });
    }

    // 3. Handle Framework Specific Tooltips or Effects
    const framework = "{{ framework }}";
    if (framework === 'fastapi') {
        console.log("⚡ Async Engine: FastAPI detected");
    }
});