<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ project_name }} | {{ APP_NAME }}</title>
    
    <link rel="stylesheet" href="/static/style.css">

    <script>
        (function() {
            const saved = localStorage.getItem('theme');
            const dark = window.matchMedia('(prefers-color-scheme: dark)').matches;
            document.documentElement.setAttribute('data-theme', saved || (dark ? 'dark' : 'light'));
        })();
    </script>
</head>
<body class="{{ framework }} {{ project_name | lower }}-engine">

    <nav class="nav">
        <div class="nav-content">
            <span class="logo">🚀 {{ project_name }}</span>
            <div class="nav-links" style="display: flex; align-items: center; gap: 1.5rem;">
                
                {# Logic: FastAPI gets Swagger, others get Repo Docs #}
                {% if framework == 'fastapi' %}
                <a href="/docs" target="_blank" class="nav-link">Swagger UI</a>
                {% else %}
                <a href="https://github.com/techquanta/community-init-api" target="_blank" class="nav-link">Docs</a>
                {% endif %}

                <a href="https://github.com/techquanta/community-init-api" 
                   target="_blank" 
                   class="github-btn" 
                   style="display: flex; align-items: center; gap: 8px; text-decoration: none;">
                    <svg height="20" width="20" viewBox="0 0 16 16" fill="currentColor">
                        <path d="M8 0C3.58 0 0 3.58 0 8c0 3.54 2.29 6.53 5.47 7.59.4.07.55-.17.55-.38 0-.19-.01-.82-.01-1.49-2.01.37-2.53-.49-2.69-.94-.09-.23-.48-.94-.82-1.13-.28-.15-.68-.52-.01-.53.63-.01 1.08.58 1.23.82.72 1.21 1.87.87 2.33.66.07-.52.28-.87.51-1.07-1.78-.2-3.64-.89-3.64-3.95 0-.87.31-1.59.82-2.15-.08-.2-.36-1.02.08-2.12 0 0 .67-.21 2.2.82.64-.18 1.32-.27 2-.27.68 0 1.36.09 2 .27 1.53-1.04 2.2-.82 2.2-.82.44 1.1.16 1.92.08 2.12.51.56.82 1.27.82 2.15 0 3.07-1.87 3.75-3.65 3.95.29.25.54.73.54 1.48 0 1.07-.01 1.93-.01 2.2 0 .21.15.46.55.38A8.013 8.013 0 0016 8c0-4.42-3.58-8-8-8z"></path>
                    </svg>
                    <span>Community</span>
                </a>

                <button id="theme-toggle" class="theme-toggle" aria-label="Toggle Theme">
                    <div class="toggle-circle"></div>
                </button>
            </div>
        </div>
    </nav>

    <main class="container">
        <header class="hero">
            <h1 class="{{ project_name | lower }}-title">{{ project_name }}<span class="dot">.</span></h1>
            <p class="tagline">{{ DESCRIPTIONS[framework] }}</p>
        </header>
        
        <section class="stack-box">
            <h3>Deployment Matrix</h3>
            <div class="grid">
                <div class="grid-item">
                    <label>Framework Port</label>
                    <span>{{ DEFAULT_PORTS[framework] }}</span>
                </div>
                <div class="grid-item">
                    <label>Architecture</label>
                    <span>{{ build_strategy | capitalize }} Mode</span>
                </div>
                {% if build_strategy == 'production' %}
                <div class="grid-item">
                    <label>DevOps Assets</label>
                    <span>Docker + GitHub CI</span>
                </div>
                {% endif %}
            </div>
        </section>

        <div class="tech-stack-row">
            <img src="https://cdn.worldvectorlogo.com/logos/python-5.svg" alt="Python">
            <img src="https://raw.githubusercontent.com/simple-icons/simple-icons/develop/icons/{{ 'fastapi' if framework == 'fastapi' else 'flask' }}.svg" alt="FW">
            {% if build_strategy == 'production' %}
            <img src="https://cdn.worldvectorlogo.com/logos/docker.svg" alt="Docker">
            {% endif %}
        </div>
    </main>

    <footer class="footer">
        <div class="footer-content">
            <p>✨ Generated by <strong>{{ APP_NAME }}</strong> • v{{ __version__ }}</p>
            <p class="tag">{{ APP_TAGLINE }}</p>
        </div>
    </footer>

</body>
</html>